version: '2'
services:

  nginx:
    build:
      context: .
      dockerfile: nginx-Dockerfile
    container_name: nginx
    ports:
      - 80:80
    links:
      - php7
    volumes:
      - ./client:/var/www/html
    volumes_from:
      - php7

  php7:
    build:
      context: .
      dockerfile: php7-Dockerfile
    container_name: php7
    links:
      - mariadb
    expose:
      - 9000
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes_from:
      - data
    environment:
      - MYSQL_ROOT_PASSWORD=devroot
      - MYSQL_DATABASE=devproject
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpassword

  data:
    image: mariadb
    container_name: data
    volumes:
      - /var/lib/mysql
    command: "true"